# Generated by Django 4.2.11 on 2024-04-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0024_order_orderitem_remove_cartorderitems_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('content', models.CharField(max_length=1000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogpictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='blog-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_images', to='rarechild.blog')),
            ],
        ),
    ]
