# Generated by Django 4.2.11 on 2024-04-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0025_blog_blogpictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='blogpictures',
            options={'verbose_name_plural': 'BlogPictures'},
        ),
    ]
